baseURL = 'https://lw.dev.br/blog/'
languageCode = 'pt-BR'
defaultContentLanguage = 'pt-br'
title = '@vouxique'
theme = 'default'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]