baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Início'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
